# Generated by Django 5.0.1 on 2025-01-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ehcpaudit',
            options={'ordering': ['-visit_date', 'ehcp_name']},
        ),
    ]
