# Generated by Django 5.0.1 on 2025-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_ehcpaudit_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='missing_records',
            new_name='has_package',
        ),
        migrations.AddField(
            model_name='patient',
            name='case_files',
            field=models.FileField(blank=True, null=True, upload_to='patient_files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='case_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='incomplete_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='package_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='package_upcoding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='total_oope',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='package_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
