# Generated by Django 5.0.1 on 2025-01-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_rename_missing_records_patient_has_package_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='has_package',
            new_name='missing_records',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='case_files',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='case_summary',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='incomplete_record',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='package_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='package_upcoding',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='total_oope',
        ),
        migrations.AlterField(
            model_name='patient',
            name='package_name',
            field=models.CharField(max_length=200),
        ),
    ]
