# Generated by Django 5.0.1 on 2025-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_make_remarks_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'ordering': ['name'], 'permissions': [('view_district_data', 'Can view district data'), ('edit_district_data', 'Can edit district data')], 'verbose_name': 'Coordinator', 'verbose_name_plural': 'Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-admission_date'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='cash_collection',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='falsification',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='medicine_charges',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='other_fraud',
        ),
        migrations.AlterField(
            model_name='patient',
            name='missing_records',
            field=models.BooleanField(default=False, verbose_name='Mandatory Records'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='money_collection',
            field=models.BooleanField(default=False, verbose_name='Money Collection'),
        ),
    ]
