# Generated by Django 5.0.1 on 2025-02-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_alter_coordinator_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehcpaudit',
            name='abuse_type',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='denial_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='ghost_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='has_audit_findings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='has_fraudulent_activities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='has_hnqa_findings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='human_resource_findings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='impersonation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='infrastructure_findings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='oope_type',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='opd_to_ipd_conversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='other_services_findings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
