# Generated by Django 5.0.1 on 2025-02-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_alter_ehcpaudit_audit_findings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='audit_findings',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='hnqa_related',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='other_fraudulent_activities',
        ),
    ]
