# Generated by Django 5.0.1 on 2025-02-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_remove_ehcpaudit_audit_findings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='documentation_score',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='feedback_score',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='infrastructure_score',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='service_score',
        ),
    ]
