# Generated by Django 5.0.1 on 2025-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_remove_ehcpaudit_documentation_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehcpaudit',
            name='cash_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='documentation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='falsification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='feedback_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='infrastructure_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='medicine_charges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='other_fraud',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='service_score',
            field=models.IntegerField(default=0),
        ),
    ]
