# Generated by Django 5.0.1 on 2025-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_ehcpaudit_cash_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='cash_collection',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='falsification',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='medicine_charges',
        ),
        migrations.RemoveField(
            model_name='ehcpaudit',
            name='other_fraud',
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='audit_findings',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='hnqa_related',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='other_fraudulent_activities',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
