# Generated by Django 5.1.6 on 2025-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_remove_ehcpaudit_cash_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehcpaudit',
            name='audit_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ehcpaudit',
            name='hnqa_related',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ehcpaudit',
            name='other_fraudulent_activities',
            field=models.TextField(blank=True),
        ),
    ]
