# Generated by Django 5.1.6 on 2025-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_alter_ehcpaudit_audit_findings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehcpaudit',
            name='audit_findings',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='ehcpaudit',
            name='hnqa_related',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='ehcpaudit',
            name='other_fraudulent_activities',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
