# Generated by Django 5.1.6 on 2025-02-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_remove_ehcpaudit_audit_findings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehcpaudit',
            name='abuse',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='abuse_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='audit_findings',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='denial_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='denial_of_service',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='oope',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='ehcpaudit',
            name='oope_details',
            field=models.TextField(blank=True),
        ),
    ]
