# Generated by Django 5.1.6 on 2025-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_remove_ehcpaudit_abuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='digital_signature',
            field=models.TextField(blank=True, null=True, verbose_name='Digital Signature'),
        ),
    ]
