# Generated by Django 5.1.6 on 2025-02-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0025_patient_digital_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EHCPAudit',
            new_name='FieldAudit',
        ),
    ]
